### ISSUE TITLE
Picking one from team should exit early if one from team already assigned to review

### ISSUE THREAD

**Issue by DillonStreator** [rowi1de/auto-assign-review-teams#125]
I believe there should be an early return if `pick-one-from-persons-or-team` and `teams` are both set and there is already a reviewer assigned from that team on the PR.

https://github.com/rowi1de/auto-assign-review-teams/blob/2b3edce251f160854a72925592354bde5c66ee38/src/main.ts#L107-L139

**Comment by rowi1de** [comment]
Added you as collaborator, want to make a suggestion in the PR?

**Comment by rowi1de** [comment]
https://github.com/rowi1de/auto-assign-review-teams/pull/59
