### ISSUE TITLE
Incorrect version number in README

### ISSUE THREAD

**Issue by spokenbird** [rowi1de/auto-assign-review-teams#23]
The readme example lists,`uses: rowi1de/auto-assign-review-teams@v.1.0.1` which is incorrect. Fixed by changing the `v1.0.1` to `v.1.0.1`.

As is it throws an errror when running the action: `An action could not be found at the URI 'https://api.github.com/repos/rowi1de/auto-assign-review-teams/tarball/v1.0.1'`

**Comment by rowi1de** [comment]
https://github.com/rowi1de/auto-assign-review-teams/releases/tag/v1.0.1 is released now
