### ISSUE TITLE
Excluding PR author doesn't work

### ISSUE THREAD

**Issue by adipatel** [rowi1de/auto-assign-review-teams#31]

**Comment by rowi1de** [comment]
@adipatel do you have an example PR?

**Comment by rowi1de** [comment]
misising infos

**Comment by fatihyildizhan** [comment]
Hi,

When the author creates a pull request, this error occures. Is it possible to add author as a reviewer too or exclude from the action?

`Error: Unknown errorHttpError: Review cannot be requested from pull request author.`

Thank you
