### ISSUE TITLE
question: why keep node_modules on repo

### ISSUE THREAD

**Issue by sinchang** [rowi1de/auto-assign-review-teams#8]
if has `npm ci` command on the ci pipeline will install deps automatically. thx

**Comment by rowi1de** [comment]
Hey @sinchang I followed this steps: https://github.com/actions/typescript-action#publish-to-a-distribution-branch 
You mean I could just throw away the folder?

**Comment by rowi1de** [comment]
@

**Comment by sinchang** [comment]
sorry about that. I created a new pull request to resolve this issue.
